import "./globals.css";
//import { Inter } from 'next/font/google'
import { ClerkProvider } from "@clerk/nextjs";
import SideNav from "./components/SideNav";
import TopNav from "./components/TopNav";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className="bg-zinc-900 text-zinc-200">
          <div className="flex flex-col border-2 border-green-500 h-screen">
          <TopNav/>
            <div className="flex border-2 border-blue-500 flex-1">
              <SideNav />
              {children}
            </div>
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
